using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Performish.Core.Benchmark;
using Performish.Core.Scanner;
using Performish.Core.Tweaks;

namespace Performish.Core.Reporting
{
    /// <summary>What a report is built from - a snapshot, its health score, and (optionally) the
    /// results of one batch and its before/after benchmark. Pure data, no I/O, so ReportWriter is
    /// trivially unit-testable: build a ReportData by hand, render it, assert on the HTML string.</summary>
    public sealed class ReportData
    {
        public DateTime GeneratedAtUtc { get; set; } = DateTime.UtcNow;
        public string MachineName { get; set; }
        public SystemSnapshot Scan { get; set; }
        public HealthScoreResult HealthBefore { get; set; }
        public HealthScoreResult HealthAfter { get; set; }
        public List<TweakRunResult> BatchResults { get; set; }
        public bool WasDryRun { get; set; }
        public BenchmarkComparison Benchmark { get; set; }

        /// <summary>The real, measured-timing benchmark comparison (CPU/memory/disk/... - see
        /// Performish.Core.Benchmark) - distinct from <see cref="Benchmark"/>, which is the cheap,
        /// count-based one. Both can be present at once; rendered as separate sections so the reader
        /// never confuses a real sampled measurement with a simple before/after count.</summary>
        public BenchmarkComparisonReport RealBenchmark { get; set; }
    }

    /// <summary>Builds a single self-contained HTML file (inline CSS, no external resources - so it
    /// opens correctly regardless of where it's saved or emailed) summarizing a scan and, if
    /// available, one apply/revert batch's outcome. Used by both the CLI's --report flag and the
    /// UI's "Export report" button, so a headless run and an interactive one produce byte-identical
    /// report structure for the same data. Every number here comes from ReportData - this class
    /// never measures anything itself, only renders what it's given ("report measured numbers only").</summary>
    public static class HtmlReportWriter
    {
        public static string Render(ReportData data)
        {
            var sb = new StringBuilder();
            sb.Append("<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>Performish report</title>");
            sb.Append("<style>");
            sb.Append("body{background:#000;color:#dcdcdc;font-family:Consolas,monospace;padding:24px;}");
            sb.Append("h1{color:#57f287;}h2{color:#57f287;border-bottom:1px solid #333;padding-bottom:4px;}");
            sb.Append("table{border-collapse:collapse;width:100%;margin-bottom:20px;}");
            sb.Append("td,th{padding:4px 10px;text-align:left;border-bottom:1px solid #222;}");
            sb.Append(".dim{color:#828282;}.accent{color:#57f287;}.bright{color:#b4ffcd;}.err{color:#f05a5a;}.mid{color:#e6d25a;}");
            sb.Append("</style></head><body>");

            sb.Append("<h1>Performish report</h1>");
            sb.Append($"<p class=\"dim\">Generated {Escape(data.GeneratedAtUtc.ToString("u"))}" +
                (string.IsNullOrEmpty(data.MachineName) ? "" : $" on {Escape(data.MachineName)}") + "</p>");

            if (data.Scan != null) RenderScanSection(sb, data.Scan, data.HealthBefore);
            if (data.BatchResults != null) RenderBatchSection(sb, data);
            if (data.Benchmark != null) RenderBenchmarkSection(sb, data.Benchmark);
            if (data.RealBenchmark != null) RenderRealBenchmarkSection(sb, data.RealBenchmark);
            if (data.HealthAfter != null) RenderHealthComparisonSection(sb, data.HealthBefore, data.HealthAfter);

            sb.Append("<p class=\"dim\">Generated by Performish. Measured results only - nothing here is estimated.</p>");
            sb.Append("</body></html>");
            return sb.ToString();
        }

        private static void RenderScanSection(StringBuilder sb, SystemSnapshot s, HealthScoreResult health)
        {
            sb.Append("<h2>System</h2><table>");
            Row(sb, "Windows", $"{s.WindowsProductName} ({s.WindowsEdition}), build {s.BuildNumber}.{s.UpdateBuildRevision}");
            Row(sb, "CPU", $"{s.CpuName} ({s.CpuCoreCount} cores / {s.CpuLogicalProcessorCount} threads)");
            Row(sb, "GPU", s.Gpus.Count == 0 ? "(none detected)" : string.Join(", ", s.Gpus.Select(g => $"{g.Name} [{g.Vendor}]")));
            Row(sb, "Memory", $"{FormatBytes(s.UsedRamBytes)} used / {FormatBytes(s.TotalRamBytes)} total");
            Row(sb, "Disk (system drive)", $"{FormatBytes(s.FreeDiskSpaceBytes)} free of {FormatBytes(s.TotalDiskSpaceBytes)}");
            Row(sb, "Uptime", $"{s.UptimeHours:0.0} hour(s)");
            Row(sb, "Power plan", s.ActivePowerPlanName);
            Row(sb, "Processes / services running / startup items", $"{s.ProcessCount} / {s.Services.Count(sv => sv.Running)} / {s.StartupItems.Count}");
            if (health != null) Row(sb, "Health score", $"{health.Score}/{HealthScore.TotalMax}");
            if (s.DetectedManagementAgents.Count > 0) Row(sb, "Detected management/security software", string.Join(", ", s.DetectedManagementAgents));
            sb.Append("</table>");
        }

        private static void RenderBatchSection(StringBuilder sb, ReportData data)
        {
            var succeeded = data.BatchResults.Count(r => !r.Failed);
            var failed = data.BatchResults.Count(r => r.Failed);
            sb.Append("<h2>Batch result" + (data.WasDryRun ? " (dry run)" : "") + "</h2>");
            sb.Append($"<p>{succeeded} succeeded, {failed} failed, {data.BatchResults.Count} total.</p>");
            sb.Append("<table><tr><th>Title</th><th>Outcome</th><th>Message</th><th class=\"dim\">Id</th></tr>");
            foreach (var r in data.BatchResults)
            {
                var cssClass = r.Failed ? "err" : "accent";
                sb.Append("<tr>");
                sb.Append($"<td>{Escape(r.Tweak.Title)}</td>");
                sb.Append($"<td class=\"{cssClass}\">{Escape(r.Result?.Outcome.ToString() ?? "Failed")}</td>");
                sb.Append($"<td class=\"dim\">{Escape(r.Result?.Message ?? r.Exception?.Message ?? "")}</td>");
                sb.Append($"<td class=\"dim\">{Escape(r.Tweak.Id)}</td>");
                sb.Append("</tr>");
            }
            sb.Append("</table>");
        }

        private static void RenderBenchmarkSection(StringBuilder sb, BenchmarkComparison c)
        {
            sb.Append("<h2>Before / after (measured)</h2><table>");
            Row(sb, "RAM used", $"{(c.UsedRamDeltaBytes <= 0 ? "" : "+")}{FormatBytes(c.UsedRamDeltaBytes)}");
            Row(sb, "Process count", $"{(c.ProcessCountDelta <= 0 ? "" : "+")}{c.ProcessCountDelta}");
            Row(sb, "Services running", $"{(c.RunningServiceCountDelta <= 0 ? "" : "+")}{c.RunningServiceCountDelta}");
            Row(sb, "Boot-impact items (proxy, not measured boot time)", $"{(c.BootImpactItemCountDelta <= 0 ? "" : "+")}{c.BootImpactItemCountDelta}");
            sb.Append("</table>");
        }

        /// <summary>The real, sampled-timing benchmark comparison - CPU/memory/disk/network/gaming
        /// metrics, each with its before/after median, percent change, and a plain-language read.
        /// Never renders a fabricated number: an Unavailable/Unreliable metric shows exactly that,
        /// same as the on-screen BenchmarkComparisonForm.</summary>
        private static void RenderRealBenchmarkSection(StringBuilder sb, BenchmarkComparisonReport report)
        {
            sb.Append("<h2>Real benchmark comparison (measured)</h2>");
            if (report.HealthScoreDelta.HasValue)
                sb.Append($"<p>Health score change: {(report.HealthScoreDelta >= 0 ? "+" : "")}{report.HealthScoreDelta}</p>");
            if (report.AttributionDisclaimer != null)
                sb.Append($"<p class=\"mid\">{Escape(report.AttributionDisclaimer)}</p>");

            sb.Append("<table><tr><th>Metric</th><th>Before</th><th>After</th><th>Change</th><th>Result</th></tr>");
            foreach (var m in report.Metrics)
            {
                var cssClass = m.Verdict switch
                {
                    ComparisonVerdict.Improved => "accent",
                    ComparisonVerdict.Worse => "err",
                    ComparisonVerdict.Unreliable => "mid",
                    _ => "dim"
                };
                var before = m.Before.HasValue ? $"{m.Before.Value:0.##} {m.Unit}" : "-";
                var after = m.After.HasValue ? $"{m.After.Value:0.##} {m.Unit}" : "-";
                var change = m.DeltaAbsolute.HasValue
                    ? $"{(m.DeltaAbsolute >= 0 ? "+" : "")}{m.DeltaAbsolute.Value:0.##} {m.Unit}" +
                      (m.DeltaPercent.HasValue ? $" ({(m.DeltaPercent >= 0 ? "+" : "")}{m.DeltaPercent.Value:0.#}%)" : "")
                    : "-";

                sb.Append("<tr>");
                sb.Append($"<td>{Escape(m.Name)}</td>");
                sb.Append($"<td class=\"dim\">{Escape(before)}</td>");
                sb.Append($"<td class=\"dim\">{Escape(after)}</td>");
                sb.Append($"<td class=\"{cssClass}\">{Escape(change)}</td>");
                sb.Append($"<td class=\"{cssClass}\">{Escape(m.Verdict.ToString())} - {Escape(m.PlainLanguageRead)}</td>");
                sb.Append("</tr>");
            }
            sb.Append("</table>");
        }

        private static void RenderHealthComparisonSection(StringBuilder sb, HealthScoreResult before, HealthScoreResult after)
        {
            sb.Append("<h2>Health score change</h2><table>");
            Row(sb, "Before", before != null ? $"{before.Score}/{HealthScore.TotalMax}" : "n/a");
            Row(sb, "After", $"{after.Score}/{HealthScore.TotalMax}");
            sb.Append("</table>");
        }

        private static void Row(StringBuilder sb, string label, string value) =>
            sb.Append($"<tr><td class=\"dim\">{Escape(label)}</td><td>{Escape(value)}</td></tr>");

        private static string FormatBytes(long bytes) => $"{bytes / 1024.0 / 1024.0 / 1024.0:0.0} GB";

        private static string Escape(string s) => System.Net.WebUtility.HtmlEncode(s ?? "");
    }
}
